import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { BrainCircuit, Lightbulb, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function DecisionWorkspace() {
  return (
    <div className="p-8 space-y-6 bg-slate-950 min-h-screen text-slate-100 font-sans border-t border-slate-800">
        
        <div className="border-b border-slate-800 pb-4 mb-6">
            <h2 className="text-2xl font-bold flex items-center gap-2 text-slate-200">
                <BrainCircuit className="text-fuchsia-400" />
                AI Strategic Decision Support
            </h2>
            <p className="text-slate-400 mt-1">Actionable recommendations generated by analyzing cross-domain telemetry and business impact.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            <DecisionCard 
                title="Accelerate Payments API Modernization"
                summary="Attack path simulations indicate the legacy authentication on the Payments API is the most viable route for critical data exfiltration. Given its MISSION CRITICAL business impact, this requires immediate prioritization."
                recs={[
                    "Reallocate 2 FTEs from internal IT projects to the API security team.",
                    "Mandate OAuth2 implementation by end of Q4.",
                    "Deploy targeted WAF rules as an interim mitigating control."
                ]}
            />

            <DecisionCard 
                title="Consolidate EDR and NDR Tooling"
                summary="Detection gap analysis shows significant overlap between current EDR and NDR tools, while Cloud coverage remains weak. Consolidating the endpoint/network stack can free up budget."
                recs={[
                    "Initiate RFP for a unified XDR platform.",
                    "Reinvest projected 15% savings into Cloud Native Application Protection Platform (CNAPP).",
                    "Target Q1 for vendor consolidation phase 1."
                ]}
            />

        </div>
    </div>
  );
}

function DecisionCard({ title, summary, recs }: any) {
    return (
        <Card className="bg-slate-900 border-slate-800 hover:border-fuchsia-900/50 transition-colors">
            <CardContent className="p-6">
                <div className="flex items-center gap-2 mb-4 text-fuchsia-400">
                    <Lightbulb size={20} />
                    <h3 className="text-lg font-bold text-slate-200">{title}</h3>
                </div>
                
                <p className="text-sm text-slate-400 mb-6 leading-relaxed bg-slate-950/50 p-4 rounded border border-slate-800/50">
                    {summary}
                </p>
                
                <div className="space-y-3 mb-6">
                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Recommended Actions</h4>
                    {recs.map((rec: string, i: number) => (
                        <div key={i} className="flex items-start gap-2 text-sm text-slate-300">
                            <ArrowRight size={16} className="text-fuchsia-500 flex-shrink-0 mt-0.5" />
                            {rec}
                        </div>
                    ))}
                </div>

                <div className="flex gap-2 border-t border-slate-800 pt-4">
                    <Button className="bg-fuchsia-600 hover:bg-fuchsia-700 text-white flex-1">
                        Approve Strategy
                    </Button>
                    <Button variant="outline" className="bg-slate-900 border-slate-700 text-slate-300 flex-1">
                        Request Alternatives
                    </Button>
                </div>
            </CardContent>
        </Card>
    );
}
