import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Zap, Wrench, ArrowUpRight } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

export default function OptimizationWorkspace() {
  return (
    <div className="p-8 space-y-6 bg-slate-950 min-h-screen text-slate-100 font-sans border-t border-slate-800">
        
        <div className="border-b border-slate-800 pb-4 mb-6">
            <h2 className="text-2xl font-bold flex items-center gap-2 text-slate-200">
                <Zap className="text-emerald-400" />
                AI Optimization Workspace
            </h2>
            <p className="text-slate-400 mt-1">Actionable, prioritized recommendations generated by the Continuous Validation engine to improve Apex score.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <RecommendationCard 
                domain="DETECTION_ENGINEERING"
                title="Deploy Sysmon Rule for LSASS Dumping"
                description="Red Team campaigns frequently succeed using Mimikatz on Tier 2 endpoints. Deploying targeted Sysmon Event ID 10 rules will close this coverage gap."
                priority="HIGH"
                expectedGain="+2.4"
            />
            
            <RecommendationCard 
                domain="SOC_WORKFLOW"
                title="Automate Triage for 'Impossible Travel' Alerts"
                description="These alerts have a 95% FP rate and consume 40 hours of analyst time weekly. Automating initial context gathering via SOAR will improve Analyst Readiness scores."
                priority="MEDIUM"
                expectedGain="+1.1"
            />
        </div>
    </div>
  );
}

function RecommendationCard({ domain, title, description, priority, expectedGain }: any) {
    let prioColor = "bg-sky-500/10 text-sky-400 border-sky-500/20";
    if (priority === 'HIGH') prioColor = "bg-rose-500/10 text-rose-400 border-rose-500/20";
    if (priority === 'MEDIUM') prioColor = "bg-amber-500/10 text-amber-400 border-amber-500/20";

    return (
        <Card className="bg-slate-900 border-slate-800 hover:border-emerald-900/50 transition-colors cursor-pointer group">
            <CardContent className="p-6">
                <div className="flex justify-between items-start mb-4">
                    <span className="text-[10px] font-bold text-slate-500 uppercase flex items-center gap-1">
                        <Wrench size={12} /> {domain}
                    </span>
                    <span className={`text-[10px] font-bold px-2 py-1 rounded border ${prioColor}`}>
                        {priority} PRIORITY
                    </span>
                </div>
                
                <h3 className="text-lg font-bold text-slate-200 mb-2 group-hover:text-emerald-400 transition-colors">{title}</h3>
                <p className="text-sm text-slate-400 mb-6">{description}</p>
                
                <div className="flex justify-between items-center border-t border-slate-800 pt-4">
                    <div className="flex flex-col">
                        <span className="text-[10px] text-slate-500 font-bold uppercase">Expected Posture Impact</span>
                        <span className="text-emerald-400 font-black flex items-center gap-1 text-lg">
                            <ArrowUpRight size={16} /> {expectedGain} pts
                        </span>
                    </div>
                    
                    <button className="text-xs font-bold text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded transition-colors">
                        Review Plan
                    </button>
                </div>
            </CardContent>
        </Card>
    );
}
