import uuid
from typing import List
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text, JSON, Float
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base_class import Base

class CloudTelemetryEvent(Base):
    __tablename__ = "mf_cdr_telemetry"
    """
    Normalized log entry (from CloudTrail, Azure Activity, etc).
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    provider: Mapped[str] = mapped_column(String(50)) # AWS, AZURE, GCP
    event_source: Mapped[str] = mapped_column(String(100)) # e.g., cloudtrail.amazonaws.com
    event_name: Mapped[str] = mapped_column(String(100)) # e.g., ConsoleLogin, DeleteBucket
    
    principal_id: Mapped[str] = mapped_column(String(255), nullable=True)
    resource_id: Mapped[str] = mapped_column(String(255), nullable=True)
    source_ip: Mapped[str] = mapped_column(String(100), nullable=True)
    
    raw_data: Mapped[dict] = mapped_column(JSON)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)


class CloudDetection(Base):
    __tablename__ = "mf_cdr_detections"
    """
    Active alert generated by analyzing telemetry.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    investigation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("mf_cdr_investigations.id", ondelete="SET NULL"), nullable=True, index=True)
    
    rule_name: Mapped[str] = mapped_column(String(255))
    severity: Mapped[str] = mapped_column(String(50)) # CRITICAL, HIGH, MEDIUM, LOW
    description: Mapped[str] = mapped_column(Text)
    
    mitre_tactics: Mapped[list] = mapped_column(JSON, default=list) # e.g., ["TA0001"]
    evidence_events: Mapped[list] = mapped_column(JSON, default=list) # List of CloudTelemetryEvent IDs
    
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class CDRCloudInvestigation(Base):
    __tablename__ = "mf_cdr_investigations"
    """
    Container linking multiple detections.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    title: Mapped[str] = mapped_column(String(255))
    status: Mapped[str] = mapped_column(String(50), default="OPEN") # OPEN, IN_PROGRESS, RESOLVED, CLOSED
    priority: Mapped[str] = mapped_column(String(50), default="MEDIUM")
    
    primary_entity: Mapped[str] = mapped_column(String(255)) # The shared identity or resource linking the detections
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class ResponseAction(Base):
    __tablename__ = "mf_cdr_response_actions"
    """
    Proposed containment or remediation action.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    investigation_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("mf_cdr_investigations.id", ondelete="CASCADE"), index=True)
    
    action_type: Mapped[str] = mapped_column(String(100)) # e.g., "REVOKE_IAM_ROLE", "ISOLATE_INSTANCE"
    target_entity: Mapped[str] = mapped_column(String(255))
    description: Mapped[str] = mapped_column(Text)
    
    status: Mapped[str] = mapped_column(String(50), default="PENDING_APPROVAL") # PENDING_APPROVAL, APPROVED, REJECTED, EXECUTED
    approver_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
