import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text, JSON, Float
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base

class SecurityPostureSnapshot(Base):
    __tablename__ = "mf_cv_posture_snapshots"
    """
    A continuous, overarching score encompassing Enterprise Defensive Posture.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    overall_posture_score: Mapped[float] = mapped_column(Float, default=0.0)
    
    # Sub-component scores calculated from BAS, Blue, Red, Purple platforms
    detection_maturity: Mapped[float] = mapped_column(Float, default=0.0)
    response_readiness: Mapped[float] = mapped_column(Float, default=0.0)
    control_effectiveness: Mapped[float] = mapped_column(Float, default=0.0)


class SecurityDriftRecord(Base):
    __tablename__ = "mf_cv_drift_records"
    """
    A record generated when the engine detects a significant negative deviation from a historical baseline.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    drift_type: Mapped[str] = mapped_column(String(100)) # e.g. DETECTION_DEGRADATION, CONTROL_FAILURE
    severity: Mapped[str] = mapped_column(String(50)) # LOW, MEDIUM, HIGH, CRITICAL
    
    description: Mapped[str] = mapped_column(Text)
    baseline_value: Mapped[float] = mapped_column(Float)
    current_value: Mapped[float] = mapped_column(Float)
    
    is_acknowledged: Mapped[bool] = mapped_column(Boolean, default=False)


class CVOptimizationRecommendation(Base):
    __tablename__ = "mf_cv_recommendations"
    """
    Actionable insights generated by the platform to improve the posture score.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    title: Mapped[str] = mapped_column(String(255))
    description: Mapped[str] = mapped_column(Text)
    domain: Mapped[str] = mapped_column(String(100)) # e.g. DETECTION_ENGINEERING, SOC_WORKFLOW
    
    priority: Mapped[str] = mapped_column(String(50)) # LOW, MEDIUM, HIGH
    expected_score_improvement: Mapped[float] = mapped_column(Float, default=0.0)
    
    status: Mapped[str] = mapped_column(String(50), default="OPEN") # OPEN, IN_PROGRESS, IMPLEMENTED, REJECTED
