import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text, JSON, Float
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base_class import Base

class MitreCoverageMetric(Base):
    __tablename__ = "mf_dg_mitre_metrics"
    """
    Stores the current detection success rate for a specific MITRE Tactic/Technique.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    tactic_id: Mapped[str] = mapped_column(String(50)) # e.g. TA0002
    technique_id: Mapped[str] = mapped_column(String(50)) # e.g. T1059
    technique_name: Mapped[str] = mapped_column(String(255))
    
    coverage_score: Mapped[float] = mapped_column(Float, default=0.0) # 0.0 to 100.0
    evaluated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class DetectionGapRecord(Base):
    __tablename__ = "mf_dg_gap_records"
    """
    Represents an identified blind spot in the detection architecture.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    technique_id: Mapped[str] = mapped_column(String(50))
    severity: Mapped[str] = mapped_column(String(50)) # CRITICAL, HIGH, MEDIUM, LOW
    description: Mapped[str] = mapped_column(Text)
    
    discovered_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    is_remediated: Mapped[bool] = mapped_column(Boolean, default=False)


class ControlOptimizationPlan(Base):
    __tablename__ = "mf_dg_optimization_plans"
    """
    Actionable plans generated by the engine to close identified gaps.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    gap_record_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("mf_dg_gap_records.id", ondelete="CASCADE"))
    
    title: Mapped[str] = mapped_column(String(255))
    description: Mapped[str] = mapped_column(Text)
    target_platform: Mapped[str] = mapped_column(String(100)) # e.g., SPLUNK, CROWDSTRIKE, AWS_GUARDDUTY
    
    expected_coverage_increase: Mapped[float] = mapped_column(Float)
    status: Mapped[str] = mapped_column(String(50), default="BACKLOG") # BACKLOG, IN_PROGRESS, IMPLEMENTED
