import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base

class ExecutiveMetric(Base):
    __tablename__ = "exec_metrics"
    """
    Time-series rollup table storing daily/hourly metrics (e.g., Total Incidents, MTTA, MTTR).
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    metric_name: Mapped[str] = mapped_column(String(100), index=True) # e.g., 'MTTR_HOURS', 'TOTAL_INCIDENTS_CRITICAL'
    metric_value: Mapped[float] = mapped_column(Float)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)


class BusinessRiskScore(Base):
    __tablename__ = "exec_business_risk_scores"
    """
    Tracks the calculated risk score for specific business units over time.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    business_unit: Mapped[str] = mapped_column(String(100), index=True)
    risk_score: Mapped[int] = mapped_column(Integer) # 0-100 scale
    factors: Mapped[dict] = mapped_column(JSON, default=dict) # e.g., {"critical_incidents": 2, "unmitigated_cves": 15}
    
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)


class ExecutiveReport(Base):
    __tablename__ = "exec_reports"
    """
    Stored AI-generated weekly/monthly summaries for board presentations.
    """
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"), index=True)
    
    report_type: Mapped[str] = mapped_column(String(50)) # WEEKLY_SUMMARY, MONTHLY_BOARD_REPORT
    title: Mapped[str] = mapped_column(String(255))
    content: Mapped[str] = mapped_column(Text) # Markdown content generated by AI
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
