from sqlalchemy import Column, String, Float, Enum, JSON, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
import uuid
from datetime import datetime
from app.db.base_class import Base

class ExplanationRecord(Base):
    """
    Stores the final narratives and insights generated by the XAI Engine.
    Maps 1-to-1 with a DecisionRecord.
    """
    __tablename__ = "xai_explanations"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    decision_id = Column(String, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Generated Narratives
    executive_summary = Column(Text, nullable=False)
    technical_summary = Column(Text, nullable=False)
    
    # JSON arrays for structured visualization data
    confidence_breakdown = Column(JSON, default=list) # e.g. [{"factor": "KG Density", "impact": 0.4}]
    feature_importance = Column(JSON, default=list) # e.g. [{"feature": "IP Blacklist", "rank": 1}]
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # We do not need a direct back_populates to decisions unless we want bi-directional, 
    # but for XAI it's fine to just query by decision_id.
    
class EvidenceAttribution(Base):
    """
    Links specific evidence back to the decision with a calculated importance weight.
    """
    __tablename__ = "xai_evidence_attribution"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    explanation_id = Column(String, ForeignKey("xai_explanations.id", ondelete="CASCADE"), nullable=False, index=True)
    evidence_link_id = Column(String, ForeignKey("decision_evidence_links.id", ondelete="CASCADE"), nullable=False)
    
    importance_weight = Column(Float, nullable=False) # 0.0 to 1.0
    attribution_text = Column(String, nullable=False) # "Provides direct link to APT-29 infrastructure"
    
    explanation = relationship("ExplanationRecord", backref="attributions")
