import React from 'react';
import './PredictiveStyles.css';

export const PredictionDashboard: React.FC = () => {
  return (
    <div className="pred-container">
      <header className="pred-header">
        <h1>Predictive Threat Intelligence</h1>
        <p className="pred-subtitle">Evidence-backed forecasts generated by AI Pattern Discovery</p>
      </header>

      <div className="pred-metrics-grid">
        <div className="pred-metric-card glassmorphism hover-lift">
          <div className="pred-metric-icon">🔮</div>
          <div className="pred-metric-content">
            <h3>Active Forecasts</h3>
            <div className="pred-metric-value">12</div>
          </div>
        </div>
        <div className="pred-metric-card glassmorphism hover-lift">
          <div className="pred-metric-icon">🎯</div>
          <div className="pred-metric-content">
            <h3>Avg. Confidence</h3>
            <div className="pred-metric-value text-accent">78%</div>
          </div>
        </div>
        <div className="pred-metric-card glassmorphism hover-lift">
          <div className="pred-metric-icon">⚠️</div>
          <div className="pred-metric-content">
            <h3>High Risk Horizons</h3>
            <div className="pred-metric-value">3</div>
          </div>
        </div>
      </div>

      <div className="pred-panel glassmorphism">
        <div className="flex-between mb-4">
          <h2>Emerging Threats</h2>
          <button className="pred-btn-primary">Generate Forecast</button>
        </div>
        
        <div className="forecast-list">
          <div className="forecast-card hover-lift border-accent">
            <div className="flex-between">
              <h3>Likely Campaign Resurgence on domain-xyz-123</h3>
              <span className="pred-badge">INFRASTRUCTURE_REUSE</span>
            </div>
            <p className="mt-2 text-gray-300">Domain previously used by APT29. New TLS certificate detected.</p>
            <div className="mt-4 flex gap-4 text-sm">
              <span><strong>Confidence:</strong> 85%</span>
              <span><strong>Horizon:</strong> Next 14 Days</span>
            </div>
            <div className="mt-4">
              <button className="pred-btn-secondary">Explore Scenarios</button>
            </div>
          </div>

          <div className="forecast-card hover-lift">
            <div className="flex-between">
              <h3>FIN7 Shifting to Healthcare Targets</h3>
              <span className="pred-badge">CAMPAIGN_EVOLUTION</span>
            </div>
            <p className="mt-2 text-gray-300">Graph pattern indicates preparatory scanning of hospital networks.</p>
            <div className="mt-4 flex gap-4 text-sm">
              <span><strong>Confidence:</strong> 62%</span>
              <span><strong>Horizon:</strong> Next 30 Days</span>
            </div>
            <div className="mt-4">
              <button className="pred-btn-secondary">Explore Scenarios</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
