apiVersion: v1
kind: Service
metadata:
  name: phoenix-frontend-svc
  namespace: phoenix-prod
  labels:
    app: phoenix-frontend
spec:
  type: ClusterIP
  selector:
    app: phoenix-frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
