"""Add mobile models

Revision ID: 0e3786bd9433
Revises: 1e97f74c67ee
Create Date: 2026-07-24 23:58:09.281035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3786bd9433'
down_revision: Union[str, Sequence[str], None] = '1e97f74c67ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('push_token', sa.String(), nullable=True),
    sa.Column('is_biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('sync_state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_devices_device_id'), 'mobile_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_mobile_devices_id'), 'mobile_devices', ['id'], unique=False)
    op.create_index(op.f('ix_mobile_devices_user_id'), 'mobile_devices', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_mobile_devices_user_id'), table_name='mobile_devices')
    op.drop_index(op.f('ix_mobile_devices_id'), table_name='mobile_devices')
    op.drop_index(op.f('ix_mobile_devices_device_id'), table_name='mobile_devices')
    op.drop_table('mobile_devices')
    # ### end Alembic commands ###
