"""Add extension models

Revision ID: 1e97f74c67ee
Revises: 8170afa87539
Create Date: 2026-07-24 23:51:38.231669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e97f74c67ee'
down_revision: Union[str, Sequence[str], None] = '8170afa87539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('browser_type', sa.String(), nullable=True),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_devices_device_fingerprint'), 'extension_devices', ['device_fingerprint'], unique=True)
    op.create_index(op.f('ix_extension_devices_id'), 'extension_devices', ['id'], unique=False)
    op.create_index(op.f('ix_extension_devices_user_id'), 'extension_devices', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_extension_devices_user_id'), table_name='extension_devices')
    op.drop_index(op.f('ix_extension_devices_id'), table_name='extension_devices')
    op.drop_index(op.f('ix_extension_devices_device_fingerprint'), table_name='extension_devices')
    op.drop_table('extension_devices')
    # ### end Alembic commands ###
