"""Add threat intel models

Revision ID: 41f562ebb3c9
Revises: f71ebb3d15a0
Create Date: 2026-07-24 23:12:40.954196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f562ebb3c9'
down_revision: Union[str, Sequence[str], None] = 'f71ebb3d15a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.String(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('threat_classification', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_normalized_value'), 'indicator', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_indicator_type'), 'indicator', ['type'], unique=False)
    op.create_index(op.f('ix_indicator_value'), 'indicator', ['value'], unique=False)
    op.create_table('indicator_correlation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_indicator_id', sa.UUID(), nullable=False),
    sa.Column('target_indicator_id', sa.UUID(), nullable=False),
    sa.Column('correlation_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_indicator_id'], ['indicator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_indicator_id'], ['indicator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_correlation_source_indicator_id'), 'indicator_correlation', ['source_indicator_id'], unique=False)
    op.create_index(op.f('ix_indicator_correlation_target_indicator_id'), 'indicator_correlation', ['target_indicator_id'], unique=False)
    op.create_table('threat_feed_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('threat_classification', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_feed_result_indicator_id'), 'threat_feed_result', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_threat_feed_result_source'), 'threat_feed_result', ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_threat_feed_result_source'), table_name='threat_feed_result')
    op.drop_index(op.f('ix_threat_feed_result_indicator_id'), table_name='threat_feed_result')
    op.drop_table('threat_feed_result')
    op.drop_index(op.f('ix_indicator_correlation_target_indicator_id'), table_name='indicator_correlation')
    op.drop_index(op.f('ix_indicator_correlation_source_indicator_id'), table_name='indicator_correlation')
    op.drop_table('indicator_correlation')
    op.drop_index(op.f('ix_indicator_value'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_type'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_normalized_value'), table_name='indicator')
    op.drop_table('indicator')
    # ### end Alembic commands ###
