"""add_knowledge_graph

Revision ID: 8283e8797510
Revises: 5abd40c714fc
Create Date: 2026-07-25 13:21:20.104556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8283e8797510'
down_revision: Union[str, Sequence[str], None] = '5abd40c714fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'MERGED', 'DELETED', name='entitystatus'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('properties_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kg_entities_entity_type'), 'kg_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_kg_entities_name'), 'kg_entities', ['name'], unique=False)
    op.create_index(op.f('ix_kg_entities_tenant_id'), 'kg_entities', ['tenant_id'], unique=False)
    op.create_table('kg_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DELETED', name='relationshipstatus'), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('properties_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['kg_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['kg_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relationship_type', name='uq_graph_edge')
    )
    op.create_index(op.f('ix_kg_relationships_relationship_type'), 'kg_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_kg_relationships_source_id'), 'kg_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_kg_relationships_target_id'), 'kg_relationships', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kg_relationships_target_id'), table_name='kg_relationships')
    op.drop_index(op.f('ix_kg_relationships_source_id'), table_name='kg_relationships')
    op.drop_index(op.f('ix_kg_relationships_relationship_type'), table_name='kg_relationships')
    op.drop_table('kg_relationships')
    op.drop_index(op.f('ix_kg_entities_tenant_id'), table_name='kg_entities')
    op.drop_index(op.f('ix_kg_entities_name'), table_name='kg_entities')
    op.drop_index(op.f('ix_kg_entities_entity_type'), table_name='kg_entities')
    op.drop_table('kg_entities')
    # ### end Alembic commands ###
