"""add_xai_platform

Revision ID: 8876c6b4abff
Revises: 9099cdecf3cb
Create Date: 2026-07-25 13:50:13.569100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8876c6b4abff'
down_revision: Union[str, Sequence[str], None] = '9099cdecf3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xai_explanations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('technical_summary', sa.Text(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xai_explanations_decision_id'), 'xai_explanations', ['decision_id'], unique=False)
    op.create_table('xai_evidence_attribution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('explanation_id', sa.String(), nullable=False),
    sa.Column('evidence_link_id', sa.String(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.Column('attribution_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_link_id'], ['decision_evidence_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['explanation_id'], ['xai_explanations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xai_evidence_attribution_explanation_id'), 'xai_evidence_attribution', ['explanation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xai_evidence_attribution_explanation_id'), table_name='xai_evidence_attribution')
    op.drop_table('xai_evidence_attribution')
    op.drop_index(op.f('ix_xai_explanations_decision_id'), table_name='xai_explanations')
    op.drop_table('xai_explanations')
    # ### end Alembic commands ###
