"""add_decision_engine

Revision ID: 9099cdecf3cb
Revises: 8283e8797510
Create Date: 2026-07-25 13:31:21.417861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9099cdecf3cb'
down_revision: Union[str, Sequence[str], None] = '8283e8797510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('decision_type', sa.Enum('THREAT_CLASSIFICATION', 'RISK_ASSESSMENT', 'EVIDENCE_PRIORITIZATION', 'INVESTIGATION_PRIORITIZATION', 'CASE_ESCALATION', 'NEXT_STEPS', 'MITIGATION', 'EVIDENCE_GAP', 'THREAT_HUNT', 'CASE_CLOSURE', name='decisiontype'), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'POLICY_BLOCKED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'REVISED', name='decisionstate'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning_chain', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_case_id'), 'decisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_decisions_decision_type'), 'decisions', ['decision_type'], unique=False)
    op.create_index(op.f('ix_decisions_state'), 'decisions', ['state'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('decision_approval_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_approval_workflows_decision_id'), 'decision_approval_workflows', ['decision_id'], unique=False)
    op.create_table('decision_evidence_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_evidence_links_decision_id'), 'decision_evidence_links', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_links_source_id'), 'decision_evidence_links', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_evidence_links_source_id'), table_name='decision_evidence_links')
    op.drop_index(op.f('ix_decision_evidence_links_decision_id'), table_name='decision_evidence_links')
    op.drop_table('decision_evidence_links')
    op.drop_index(op.f('ix_decision_approval_workflows_decision_id'), table_name='decision_approval_workflows')
    op.drop_table('decision_approval_workflows')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_state'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_type'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_case_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
