"""add_model_manager

Revision ID: 96a008fb3aae
Revises: 8876c6b4abff
Create Date: 2026-07-25 13:57:40.047121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a008fb3aae'
down_revision: Union[str, Sequence[str], None] = '8876c6b4abff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('api_key_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k_prompt', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_completion', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_table('ai_cost_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cost_logs_tenant_id'), 'ai_cost_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_cost_logs_timestamp'), 'ai_cost_logs', ['timestamp'], unique=False)
    op.create_table('ai_routing_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('primary_model_id', sa.String(), nullable=True),
    sa.Column('fallback_model_id', sa.String(), nullable=True),
    sa.Column('max_cost_limit', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_routing_policies_capability'), 'ai_routing_policies', ['capability'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_routing_policies_capability'), table_name='ai_routing_policies')
    op.drop_table('ai_routing_policies')
    op.drop_index(op.f('ix_ai_cost_logs_timestamp'), table_name='ai_cost_logs')
    op.drop_index(op.f('ix_ai_cost_logs_tenant_id'), table_name='ai_cost_logs')
    op.drop_table('ai_cost_logs')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
