"""add_multi_agent_models

Revision ID: 9cb2e8609a56
Revises: 72db516e752e
Create Date: 2026-07-25 12:33:02.963118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb2e8609a56'
down_revision: Union[str, Sequence[str], None] = '72db516e752e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('hmac_signature', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_audit_logs_action_type'), 'agent_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_agent_id'), 'agent_audit_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_id'), 'agent_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_timestamp'), 'agent_audit_logs', ['timestamp'], unique=False)
    op.create_table('agent_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('supported_tasks_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DEPRECATED', name='agentstatus'), nullable=False),
    sa.Column('health', sa.Enum('HEALTHY', 'DEGRADED', 'UNREACHABLE', 'OFFLINE', name='agenthealth'), nullable=False),
    sa.Column('dependencies_json', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('preferred_capability', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_definitions_agent_name'), 'agent_definitions', ['agent_name'], unique=True)
    op.create_index(op.f('ix_agent_definitions_id'), 'agent_definitions', ['id'], unique=False)
    op.create_table('agent_health_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('metric_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_throughput', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_health_metrics_agent_id'), 'agent_health_metrics', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_health_metrics_id'), 'agent_health_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_agent_health_metrics_metric_timestamp'), 'agent_health_metrics', ['metric_timestamp'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('message_type', sa.Enum('REQUEST', 'RESPONSE', 'EVENT', 'BROADCAST', 'HANDOFF', name='messagetype'), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_correlation_id'), 'agent_messages', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_messages_message_type'), 'agent_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_agent_messages_receiver_id'), 'agent_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_sender_id'), 'agent_messages', ['sender_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('assigned_agent_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULING', 'RUNNING', 'COMPLETED', 'FAILED', 'WAITING_FOR_APPROVAL', 'CONFLICTED', name='taskstatus'), nullable=False),
    sa.Column('input_payload_json', sa.JSON(), nullable=False),
    sa.Column('output_findings_json', sa.JSON(), nullable=False),
    sa.Column('dependency_task_ids_json', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_assigned_agent_id'), 'agent_tasks', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_case_id'), 'agent_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_id'), 'agent_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_investigation_id'), 'agent_tasks', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_parent_id'), 'agent_tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_session_id'), 'agent_tasks', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_task_name'), 'agent_tasks', ['task_name'], unique=False)
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider_used', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=True),
    sa.Column('input_prompt_encrypted', sa.Text(), nullable=False),
    sa.Column('output_response_encrypted', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('token_input_count', sa.Integer(), nullable=False),
    sa.Column('token_output_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decision_trace_json', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hmac_signature', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_logs_id'), 'ai_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_request_id'), 'ai_audit_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_ai_audit_logs_tenant_id'), 'ai_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_timestamp'), 'ai_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_user_id'), 'ai_audit_logs', ['user_id'], unique=False)
    op.create_table('ai_capability_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_model_id', sa.String(), nullable=False),
    sa.Column('fallback_model_ids_json', sa.JSON(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_capability_mappings_capability_name'), 'ai_capability_mappings', ['capability_name'], unique=True)
    op.create_index(op.f('ix_ai_capability_mappings_id'), 'ai_capability_mappings', ['id'], unique=False)
    op.create_table('ai_memory_store',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('memory_tier', sa.Enum('SESSION', 'CASE', 'CONVERSATION', 'EVIDENCE', 'ORGANIZATION', 'USER_PREF', name='memorytier'), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('key_name', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('compressed_summary', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memory_store_case_id'), 'ai_memory_store', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_memory_store_expires_at'), 'ai_memory_store', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ai_memory_store_id'), 'ai_memory_store', ['id'], unique=False)
    op.create_index(op.f('ix_ai_memory_store_investigation_id'), 'ai_memory_store', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_ai_memory_store_key_name'), 'ai_memory_store', ['key_name'], unique=False)
    op.create_index(op.f('ix_ai_memory_store_memory_tier'), 'ai_memory_store', ['memory_tier'], unique=False)
    op.create_index(op.f('ix_ai_memory_store_session_id'), 'ai_memory_store', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_memory_store_tenant_id'), 'ai_memory_store', ['tenant_id'], unique=False)
    op.create_table('ai_policy_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_models_json', sa.JSON(), nullable=False),
    sa.Column('blocked_keywords_json', sa.JSON(), nullable=False),
    sa.Column('require_human_review_threshold', sa.Float(), nullable=False),
    sa.Column('pii_filtering_enabled', sa.Boolean(), nullable=False),
    sa.Column('residency_region', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_policy_rules_id'), 'ai_policy_rules', ['id'], unique=False)
    op.create_index(op.f('ix_ai_policy_rules_name'), 'ai_policy_rules', ['name'], unique=False)
    op.create_index(op.f('ix_ai_policy_rules_tenant_id'), 'ai_policy_rules', ['tenant_id'], unique=False)
    op.create_table('ai_prompt_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('required_variables_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prompt_templates_id'), 'ai_prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_ai_prompt_templates_name'), 'ai_prompt_templates', ['name'], unique=True)
    op.create_index(op.f('ix_ai_prompt_templates_template_type'), 'ai_prompt_templates', ['template_type'], unique=False)
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.Enum('OPENAI', 'GEMINI', 'CLAUDE', 'MISTRAL', 'DEEPSEEK', 'QWEN', 'LLAMA', 'OLLAMA', 'ENTERPRISE_LOCAL', 'CUSTOM', name='providertype'), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_provider_configs_id'), 'ai_provider_configs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_provider_configs_name'), 'ai_provider_configs', ['name'], unique=True)
    op.create_table('shared_memory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('WORKING', 'EVIDENCE', 'CONVERSATION', 'CASE', 'ORGANIZATION', 'TEMPORARY', 'PERSISTENT', name='memorytierext'), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_memory_items_expires_at'), 'shared_memory_items', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shared_memory_items_id'), 'shared_memory_items', ['id'], unique=False)
    op.create_index(op.f('ix_shared_memory_items_key'), 'shared_memory_items', ['key'], unique=False)
    op.create_index(op.f('ix_shared_memory_items_tenant_id'), 'shared_memory_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_shared_memory_items_tier'), 'shared_memory_items', ['tier'], unique=False)
    op.create_table('token_usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('date_bucket', sa.String(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_records_date_bucket'), 'token_usage_records', ['date_bucket'], unique=False)
    op.create_index(op.f('ix_token_usage_records_id'), 'token_usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_records_model'), 'token_usage_records', ['model'], unique=False)
    op.create_index(op.f('ix_token_usage_records_tenant_id'), 'token_usage_records', ['tenant_id'], unique=False)
    op.create_table('ai_model_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('max_context_tokens', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('cost_per_1k_input_usd', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_output_usd', sa.Float(), nullable=False),
    sa.Column('typical_latency_ms', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.Enum('HEALTHY', 'DEGRADED', 'UNREACHABLE', 'OFFLINE', name='modelhealthstatus'), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_entries_id'), 'ai_model_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_model_entries_model_id'), 'ai_model_entries', ['model_id'], unique=True)
    op.create_index(op.f('ix_ai_model_entries_provider_id'), 'ai_model_entries', ['provider_id'], unique=False)
    op.create_table('human_approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('requesting_agent_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_severity', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'OVERRIDDEN', name='approvalstatus'), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_approval_requests_id'), 'human_approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_human_approval_requests_status'), 'human_approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_human_approval_requests_task_id'), 'human_approval_requests', ['task_id'], unique=False)
    op.create_table('task_execution_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fallback_path_taken', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_execution_history_agent_id'), 'task_execution_history', ['agent_id'], unique=False)
    op.create_index(op.f('ix_task_execution_history_id'), 'task_execution_history', ['id'], unique=False)
    op.create_index(op.f('ix_task_execution_history_task_id'), 'task_execution_history', ['task_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_task_execution_history_task_id'), table_name='task_execution_history')
    op.drop_index(op.f('ix_task_execution_history_id'), table_name='task_execution_history')
    op.drop_index(op.f('ix_task_execution_history_agent_id'), table_name='task_execution_history')
    op.drop_table('task_execution_history')
    op.drop_index(op.f('ix_human_approval_requests_task_id'), table_name='human_approval_requests')
    op.drop_index(op.f('ix_human_approval_requests_status'), table_name='human_approval_requests')
    op.drop_index(op.f('ix_human_approval_requests_id'), table_name='human_approval_requests')
    op.drop_table('human_approval_requests')
    op.drop_index(op.f('ix_ai_model_entries_provider_id'), table_name='ai_model_entries')
    op.drop_index(op.f('ix_ai_model_entries_model_id'), table_name='ai_model_entries')
    op.drop_index(op.f('ix_ai_model_entries_id'), table_name='ai_model_entries')
    op.drop_table('ai_model_entries')
    op.drop_index(op.f('ix_token_usage_records_tenant_id'), table_name='token_usage_records')
    op.drop_index(op.f('ix_token_usage_records_model'), table_name='token_usage_records')
    op.drop_index(op.f('ix_token_usage_records_id'), table_name='token_usage_records')
    op.drop_index(op.f('ix_token_usage_records_date_bucket'), table_name='token_usage_records')
    op.drop_table('token_usage_records')
    op.drop_index(op.f('ix_shared_memory_items_tier'), table_name='shared_memory_items')
    op.drop_index(op.f('ix_shared_memory_items_tenant_id'), table_name='shared_memory_items')
    op.drop_index(op.f('ix_shared_memory_items_key'), table_name='shared_memory_items')
    op.drop_index(op.f('ix_shared_memory_items_id'), table_name='shared_memory_items')
    op.drop_index(op.f('ix_shared_memory_items_expires_at'), table_name='shared_memory_items')
    op.drop_table('shared_memory_items')
    op.drop_index(op.f('ix_ai_provider_configs_name'), table_name='ai_provider_configs')
    op.drop_index(op.f('ix_ai_provider_configs_id'), table_name='ai_provider_configs')
    op.drop_table('ai_provider_configs')
    op.drop_index(op.f('ix_ai_prompt_templates_template_type'), table_name='ai_prompt_templates')
    op.drop_index(op.f('ix_ai_prompt_templates_name'), table_name='ai_prompt_templates')
    op.drop_index(op.f('ix_ai_prompt_templates_id'), table_name='ai_prompt_templates')
    op.drop_table('ai_prompt_templates')
    op.drop_index(op.f('ix_ai_policy_rules_tenant_id'), table_name='ai_policy_rules')
    op.drop_index(op.f('ix_ai_policy_rules_name'), table_name='ai_policy_rules')
    op.drop_index(op.f('ix_ai_policy_rules_id'), table_name='ai_policy_rules')
    op.drop_table('ai_policy_rules')
    op.drop_index(op.f('ix_ai_memory_store_tenant_id'), table_name='ai_memory_store')
    op.drop_index(op.f('ix_ai_memory_store_session_id'), table_name='ai_memory_store')
    op.drop_index(op.f('ix_ai_memory_store_memory_tier'), table_name='ai_memory_store')
    op.drop_index(op.f('ix_ai_memory_store_key_name'), table_name='ai_memory_store')
    op.drop_index(op.f('ix_ai_memory_store_investigation_id'), table_name='ai_memory_store')
    op.drop_index(op.f('ix_ai_memory_store_id'), table_name='ai_memory_store')
    op.drop_index(op.f('ix_ai_memory_store_expires_at'), table_name='ai_memory_store')
    op.drop_index(op.f('ix_ai_memory_store_case_id'), table_name='ai_memory_store')
    op.drop_table('ai_memory_store')
    op.drop_index(op.f('ix_ai_capability_mappings_id'), table_name='ai_capability_mappings')
    op.drop_index(op.f('ix_ai_capability_mappings_capability_name'), table_name='ai_capability_mappings')
    op.drop_table('ai_capability_mappings')
    op.drop_index(op.f('ix_ai_audit_logs_user_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_timestamp'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_tenant_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_request_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_id'), table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')
    op.drop_index(op.f('ix_agent_tasks_task_name'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_session_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_parent_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_investigation_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_case_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_assigned_agent_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_agent_messages_sender_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_receiver_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_message_type'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_correlation_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_health_metrics_metric_timestamp'), table_name='agent_health_metrics')
    op.drop_index(op.f('ix_agent_health_metrics_id'), table_name='agent_health_metrics')
    op.drop_index(op.f('ix_agent_health_metrics_agent_id'), table_name='agent_health_metrics')
    op.drop_table('agent_health_metrics')
    op.drop_index(op.f('ix_agent_definitions_id'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_agent_name'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    op.drop_index(op.f('ix_agent_audit_logs_timestamp'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_agent_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_action_type'), table_name='agent_audit_logs')
    op.drop_table('agent_audit_logs')
    # ### end Alembic commands ###
