"""add_ai_context_models

Revision ID: a5cd245d15a8
Revises: 89c2374bd7c2
Create Date: 2026-07-25 12:52:04.959476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cd245d15a8'
down_revision: Union[str, Sequence[str], None] = '89c2374bd7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_context_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('original_tokens', sa.Integer(), nullable=True),
    sa.Column('compressed_tokens', sa.Integer(), nullable=True),
    sa.Column('build_latency_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_context_audit_logs_id'), 'ai_context_audit_logs', ['id'], unique=False)
    op.create_table('ai_context_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('assembled_context', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_context_cache_cache_key'), 'ai_context_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_ai_context_cache_id'), 'ai_context_cache', ['id'], unique=False)
    op.create_table('ai_context_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_context_policies_id'), 'ai_context_policies', ['id'], unique=False)
    op.create_table('ai_context_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_prompt', sa.Text(), nullable=False),
    sa.Column('default_max_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ai_context_templates_id'), 'ai_context_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_context_templates_id'), table_name='ai_context_templates')
    op.drop_table('ai_context_templates')
    op.drop_index(op.f('ix_ai_context_policies_id'), table_name='ai_context_policies')
    op.drop_table('ai_context_policies')
    op.drop_index(op.f('ix_ai_context_cache_id'), table_name='ai_context_cache')
    op.drop_index(op.f('ix_ai_context_cache_cache_key'), table_name='ai_context_cache')
    op.drop_table('ai_context_cache')
    op.drop_index(op.f('ix_ai_context_audit_logs_id'), table_name='ai_context_audit_logs')
    op.drop_table('ai_context_audit_logs')
    # ### end Alembic commands ###
