"""add_alert_management_models

Revision ID: e6edc99c5ce9
Revises: fk_indexes_001
Create Date: 2026-07-27 11:22:35.161319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6edc99c5ce9'
down_revision: Union[str, Sequence[str], None] = 'fk_indexes_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_alert_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_reason', sa.String(length=100), nullable=True),
    sa.Column('correlation_group_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['correlation_group_id'], ['alert_correlation_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_case_id'), 'security_alerts', ['case_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_category'), 'security_alerts', ['category'], unique=False)
    op.create_index(op.f('ix_security_alerts_correlation_group_id'), 'security_alerts', ['correlation_group_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_created_at'), 'security_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_id'), 'security_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_security_alerts_priority_score'), 'security_alerts', ['priority_score'], unique=False)
    op.create_index(op.f('ix_security_alerts_source'), 'security_alerts', ['source'], unique=False)
    op.create_index(op.f('ix_security_alerts_source_alert_id'), 'security_alerts', ['source_alert_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_status'), 'security_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_security_alerts_tenant_id'), 'security_alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_title'), 'security_alerts', ['title'], unique=False)
    op.create_table('ti_feed_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['ti_feed_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['ti_feed_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ti_feed_audit_log_feed_id'), 'ti_feed_audit_log', ['feed_id'], unique=False)
    op.create_table('ti_feed_indicator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('global_indicator_id', sa.Uuid(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['ti_feed_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_indicator_id'], ['indicator.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['ti_feed_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ti_feed_indicator_feed_id'), 'ti_feed_indicator', ['feed_id'], unique=False)
    op.create_index(op.f('ix_ti_feed_indicator_global_indicator_id'), 'ti_feed_indicator', ['global_indicator_id'], unique=False)
    op.create_index(op.f('ix_ti_feed_indicator_version_id'), 'ti_feed_indicator', ['version_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_case_id'), 'timeline_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_event_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('logs_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_version_id'), 'workflow_executions', ['version_id'], unique=False)
    op.create_table('alert_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['security_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_assignments_alert_id'), 'alert_assignments', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_assignments_id'), 'alert_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_alert_assignments_user_id'), 'alert_assignments', ['user_id'], unique=False)
    op.create_table('alert_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['security_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_evidence_alert_id'), 'alert_evidence', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_evidence_id'), 'alert_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_alert_evidence_value'), 'alert_evidence', ['value'], unique=False)
    op.create_table('alert_lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['security_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_lifecycle_events_alert_id'), 'alert_lifecycle_events', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_lifecycle_events_id'), 'alert_lifecycle_events', ['id'], unique=False)
    op.create_table('browser_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('browser_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_investigations_browser_type'), 'browser_investigations', ['browser_type'], unique=False)
    op.create_index(op.f('ix_browser_investigations_id'), 'browser_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_browser_investigations_investigation_id'), 'browser_investigations', ['investigation_id'], unique=True)
    op.create_table('cloud_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('cloud_provider', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_investigations_cloud_provider'), 'cloud_investigations', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_cloud_investigations_id'), 'cloud_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_investigations_investigation_id'), 'cloud_investigations', ['investigation_id'], unique=True)
    op.create_table('copilot_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_conversations_id'), 'copilot_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_investigation_id'), 'copilot_conversations', ['investigation_id'], unique=False)
    op.create_table('email_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_investigations_id'), 'email_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_email_investigations_investigation_id'), 'email_investigations', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_email_investigations_message_id'), 'email_investigations', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_investigations_subject'), 'email_investigations', ['subject'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    op.create_index(op.f('ix_generated_reports_investigation_id'), 'generated_reports', ['investigation_id'], unique=False)
    op.create_table('malware_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('sample_name', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_malware_investigations_id'), 'malware_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_malware_investigations_investigation_id'), 'malware_investigations', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_malware_investigations_sample_name'), 'malware_investigations', ['sample_name'], unique=False)
    op.create_table('mobile_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_investigations_device_name'), 'mobile_investigations', ['device_name'], unique=False)
    op.create_index(op.f('ix_mobile_investigations_id'), 'mobile_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_mobile_investigations_investigation_id'), 'mobile_investigations', ['investigation_id'], unique=True)
    op.create_table('network_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_investigations_id'), 'network_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_network_investigations_investigation_id'), 'network_investigations', ['investigation_id'], unique=True)
    op.create_table('qr_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_investigations_file_name'), 'qr_investigations', ['file_name'], unique=False)
    op.create_index(op.f('ix_qr_investigations_id'), 'qr_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_qr_investigations_investigation_id'), 'qr_investigations', ['investigation_id'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_data', sa.JSON(), nullable=False),
    sa.Column('rendered_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_investigation_id'), 'reports', ['investigation_id'], unique=False)
    op.create_table('url_investigation_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('url_length', sa.Integer(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('suspicious_keywords_found', sa.JSON(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_investigation_details_canonical_url'), 'url_investigation_details', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_url_investigation_details_id'), 'url_investigation_details', ['id'], unique=False)
    op.create_index(op.f('ix_url_investigation_details_investigation_id'), 'url_investigation_details', ['investigation_id'], unique=True)
    op.create_table('website_investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_investigations_id'), 'website_investigations', ['id'], unique=False)
    op.create_index(op.f('ix_website_investigations_investigation_id'), 'website_investigations', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_website_investigations_url'), 'website_investigations', ['url'], unique=False)
    op.create_table('attachment_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_investigation_id'], ['email_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_metadata_id'), 'attachment_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_attachment_metadata_sha256_hash'), 'attachment_metadata', ['sha256_hash'], unique=False)
    op.create_table('authentication_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('spf_result', sa.String(), nullable=True),
    sa.Column('dkim_result', sa.String(), nullable=True),
    sa.Column('dmarc_result', sa.String(), nullable=True),
    sa.Column('is_spoofed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_investigation_id'], ['email_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_investigation_id')
    )
    op.create_index(op.f('ix_authentication_results_id'), 'authentication_results', ['id'], unique=False)
    op.create_table('brand_intelligence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('is_typosquat', sa.Boolean(), nullable=True),
    sa.Column('typosquat_target', sa.String(), nullable=True),
    sa.Column('is_homograph', sa.Boolean(), nullable=True),
    sa.Column('homograph_target', sa.String(), nullable=True),
    sa.Column('brand_impersonation_score', sa.Float(), nullable=True),
    sa.Column('targeted_brand', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['url_investigation_id'], ['url_investigation_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_investigation_id')
    )
    op.create_index(op.f('ix_brand_intelligence_id'), 'brand_intelligence', ['id'], unique=False)
    op.create_table('browser_cookies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('creation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_secure', sa.Boolean(), nullable=True),
    sa.Column('is_httponly', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['browser_investigation_id'], ['browser_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_cookies_domain'), 'browser_cookies', ['domain'], unique=False)
    op.create_index(op.f('ix_browser_cookies_id'), 'browser_cookies', ['id'], unique=False)
    op.create_table('browser_downloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('download_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['browser_investigation_id'], ['browser_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_downloads_id'), 'browser_downloads', ['id'], unique=False)
    op.create_table('browser_extensions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('extension_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['browser_investigation_id'], ['browser_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_extensions_extension_id'), 'browser_extensions', ['extension_id'], unique=False)
    op.create_index(op.f('ix_browser_extensions_id'), 'browser_extensions', ['id'], unique=False)
    op.create_table('browser_extracted_iocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=True),
    sa.Column('ioc_value', sa.String(), nullable=True),
    sa.Column('source_context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['browser_investigation_id'], ['browser_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_extracted_iocs_id'), 'browser_extracted_iocs', ['id'], unique=False)
    op.create_table('browser_history_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('visit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('is_search', sa.Boolean(), nullable=True),
    sa.Column('search_keyword', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['browser_investigation_id'], ['browser_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_history_records_id'), 'browser_history_records', ['id'], unique=False)
    op.create_index(op.f('ix_browser_history_records_url'), 'browser_history_records', ['url'], unique=False)
    op.create_table('browser_timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_table', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['browser_investigation_id'], ['browser_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_timeline_events_id'), 'browser_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_browser_timeline_events_timestamp'), 'browser_timeline_events', ['timestamp'], unique=False)
    op.create_table('campaign_correlations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('matched_indicators', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['email_investigation_id'], ['email_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_investigation_id')
    )
    op.create_index(op.f('ix_campaign_correlations_id'), 'campaign_correlations', ['id'], unique=False)
    op.create_table('cloud_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cloud_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_investigation_id'], ['cloud_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_assets_asset_id'), 'cloud_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cloud_assets_asset_type'), 'cloud_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_cloud_assets_id'), 'cloud_assets', ['id'], unique=False)
    op.create_table('cloud_audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cloud_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_source', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_investigation_id'], ['cloud_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_audit_events_event_name'), 'cloud_audit_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_cloud_audit_events_id'), 'cloud_audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_audit_events_timestamp'), 'cloud_audit_events', ['timestamp'], unique=False)
    op.create_table('cloud_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cloud_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('config_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('is_misconfigured', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_investigation_id'], ['cloud_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_configurations_id'), 'cloud_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_configurations_resource_id'), 'cloud_configurations', ['resource_id'], unique=False)
    op.create_table('cloud_extracted_iocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cloud_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=True),
    sa.Column('ioc_value', sa.String(), nullable=True),
    sa.Column('source_context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_investigation_id'], ['cloud_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_extracted_iocs_id'), 'cloud_extracted_iocs', ['id'], unique=False)
    op.create_table('cloud_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cloud_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=True),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_highly_privileged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_investigation_id'], ['cloud_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_identities_id'), 'cloud_identities', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_identities_identity_id'), 'cloud_identities', ['identity_id'], unique=False)
    op.create_table('cloud_timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cloud_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_table', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_investigation_id'], ['cloud_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_timeline_events_id'), 'cloud_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_timeline_events_timestamp'), 'cloud_timeline_events', ['timestamp'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_conversation_id'), 'copilot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_id'), 'copilot_messages', ['id'], unique=False)
    op.create_table('decoded_qr_payloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('qr_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('raw_payload', sa.String(), nullable=True),
    sa.Column('payload_type', sa.String(), nullable=True),
    sa.Column('extracted_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['qr_investigation_id'], ['qr_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_investigation_id')
    )
    op.create_index(op.f('ix_decoded_qr_payloads_id'), 'decoded_qr_payloads', ['id'], unique=False)
    op.create_table('domain_infrastructures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('ips', sa.JSON(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('asn_org', sa.String(), nullable=True),
    sa.Column('nameservers', sa.JSON(), nullable=True),
    sa.Column('mx_records', sa.JSON(), nullable=True),
    sa.Column('txt_records', sa.JSON(), nullable=True),
    sa.Column('whois_registrar', sa.String(), nullable=True),
    sa.Column('whois_creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whois_expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['url_investigation_id'], ['url_investigation_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_investigation_id')
    )
    op.create_index(op.f('ix_domain_infrastructures_domain_name'), 'domain_infrastructures', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_infrastructures_id'), 'domain_infrastructures', ['id'], unique=False)
    op.create_table('email_header_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('date_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('return_path', sa.String(), nullable=True),
    sa.Column('reply_to', sa.String(), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=True),
    sa.Column('cc_addresses', sa.JSON(), nullable=True),
    sa.Column('raw_headers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['email_investigation_id'], ['email_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_investigation_id')
    )
    op.create_index(op.f('ix_email_header_data_id'), 'email_header_data', ['id'], unique=False)
    op.create_table('extracted_urls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_investigation_id'], ['email_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_urls_id'), 'extracted_urls', ['id'], unique=False)
    op.create_table('form_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('is_login', sa.Boolean(), nullable=True),
    sa.Column('has_password_field', sa.Boolean(), nullable=True),
    sa.Column('has_credit_card_field', sa.Boolean(), nullable=True),
    sa.Column('requests_personal_info', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['website_investigation_id'], ['website_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_metadata_id'), 'form_metadata', ['id'], unique=False)
    op.create_table('javascript_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('script_source', sa.String(), nullable=True),
    sa.Column('is_obfuscated', sa.Boolean(), nullable=True),
    sa.Column('makes_ajax_requests', sa.Boolean(), nullable=True),
    sa.Column('accesses_clipboard', sa.Boolean(), nullable=True),
    sa.Column('uses_suspicious_apis', sa.Boolean(), nullable=True),
    sa.Column('is_tracking_library', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['website_investigation_id'], ['website_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_javascript_metadata_id'), 'javascript_metadata', ['id'], unique=False)
    op.create_table('malware_extracted_iocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('malware_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=True),
    sa.Column('ioc_value', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['malware_investigation_id'], ['malware_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_malware_extracted_iocs_id'), 'malware_extracted_iocs', ['id'], unique=False)
    op.create_table('malware_hashes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('malware_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('sha1', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('ssdeep', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['malware_investigation_id'], ['malware_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('malware_investigation_id')
    )
    op.create_index(op.f('ix_malware_hashes_id'), 'malware_hashes', ['id'], unique=False)
    op.create_index(op.f('ix_malware_hashes_md5'), 'malware_hashes', ['md5'], unique=False)
    op.create_index(op.f('ix_malware_hashes_sha1'), 'malware_hashes', ['sha1'], unique=False)
    op.create_index(op.f('ix_malware_hashes_sha256'), 'malware_hashes', ['sha256'], unique=False)
    op.create_table('malware_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('malware_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('magic_bytes', sa.String(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['malware_investigation_id'], ['malware_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('malware_investigation_id')
    )
    op.create_index(op.f('ix_malware_metadata_id'), 'malware_metadata', ['id'], unique=False)
    op.create_table('malware_threat_correlations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('malware_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('matched_campaign', sa.String(), nullable=True),
    sa.Column('matched_actor', sa.String(), nullable=True),
    sa.Column('known_malware_family', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['malware_investigation_id'], ['malware_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('malware_investigation_id')
    )
    op.create_index(op.f('ix_malware_threat_correlations_id'), 'malware_threat_correlations', ['id'], unique=False)
    op.create_table('mobile_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mobile_investigation_id'], ['mobile_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_applications_id'), 'mobile_applications', ['id'], unique=False)
    op.create_index(op.f('ix_mobile_applications_package_name'), 'mobile_applications', ['package_name'], unique=False)
    op.create_table('mobile_communications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('comm_type', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mobile_investigation_id'], ['mobile_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_communications_contact_number'), 'mobile_communications', ['contact_number'], unique=False)
    op.create_index(op.f('ix_mobile_communications_id'), 'mobile_communications', ['id'], unique=False)
    op.create_table('mobile_device_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mobile_investigation_id'], ['mobile_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_investigation_id')
    )
    op.create_index(op.f('ix_mobile_device_metadata_id'), 'mobile_device_metadata', ['id'], unique=False)
    op.create_table('mobile_extracted_iocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=True),
    sa.Column('ioc_value', sa.String(), nullable=True),
    sa.Column('source_context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mobile_investigation_id'], ['mobile_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_extracted_iocs_id'), 'mobile_extracted_iocs', ['id'], unique=False)
    op.create_table('mobile_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mobile_investigation_id'], ['mobile_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_locations_id'), 'mobile_locations', ['id'], unique=False)
    op.create_table('mobile_timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_table', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mobile_investigation_id'], ['mobile_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_timeline_events_id'), 'mobile_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_mobile_timeline_events_timestamp'), 'mobile_timeline_events', ['timestamp'], unique=False)
    op.create_table('network_dns_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('response_code', sa.String(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['network_investigation_id'], ['network_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_dns_records_id'), 'network_dns_records', ['id'], unique=False)
    op.create_index(op.f('ix_network_dns_records_query'), 'network_dns_records', ['query'], unique=False)
    op.create_table('network_extracted_iocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=True),
    sa.Column('ioc_value', sa.String(), nullable=True),
    sa.Column('source_context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['network_investigation_id'], ['network_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_extracted_iocs_id'), 'network_extracted_iocs', ['id'], unique=False)
    op.create_table('network_flow_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('bytes_received', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['network_investigation_id'], ['network_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_flow_records_destination_ip'), 'network_flow_records', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_network_flow_records_id'), 'network_flow_records', ['id'], unique=False)
    op.create_index(op.f('ix_network_flow_records_source_ip'), 'network_flow_records', ['source_ip'], unique=False)
    op.create_table('network_http_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['network_investigation_id'], ['network_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_http_metadata_host'), 'network_http_metadata', ['host'], unique=False)
    op.create_index(op.f('ix_network_http_metadata_id'), 'network_http_metadata', ['id'], unique=False)
    op.create_table('network_timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_table', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['network_investigation_id'], ['network_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_timeline_events_id'), 'network_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_network_timeline_events_timestamp'), 'network_timeline_events', ['timestamp'], unique=False)
    op.create_table('network_tls_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('cipher', sa.String(), nullable=True),
    sa.Column('ja3_fingerprint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['network_investigation_id'], ['network_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_tls_metadata_id'), 'network_tls_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_network_tls_metadata_server_name'), 'network_tls_metadata', ['server_name'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('has_hidden_elements', sa.Boolean(), nullable=True),
    sa.Column('has_iframes', sa.Boolean(), nullable=True),
    sa.Column('has_meta_refresh', sa.Boolean(), nullable=True),
    sa.Column('has_suspicious_tags', sa.Boolean(), nullable=True),
    sa.Column('embedded_credentials', sa.Boolean(), nullable=True),
    sa.Column('cookies', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['website_investigation_id'], ['website_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_investigation_id')
    )
    op.create_index(op.f('ix_page_snapshots_id'), 'page_snapshots', ['id'], unique=False)
    op.create_table('parsed_urls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('root_domain', sa.String(), nullable=True),
    sa.Column('public_suffix', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('query_parameters', sa.JSON(), nullable=True),
    sa.Column('fragments', sa.String(), nullable=True),
    sa.Column('encoded_characters', sa.Boolean(), nullable=True),
    sa.Column('unicode_characters', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['url_investigation_id'], ['url_investigation_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_investigation_id')
    )
    op.create_index(op.f('ix_parsed_urls_hostname'), 'parsed_urls', ['hostname'], unique=False)
    op.create_index(op.f('ix_parsed_urls_id'), 'parsed_urls', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_urls_root_domain'), 'parsed_urls', ['root_domain'], unique=False)
    op.create_table('qr_image_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('qr_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('contains_multiple_qrs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['qr_investigation_id'], ['qr_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_investigation_id')
    )
    op.create_index(op.f('ix_qr_image_metadata_id'), 'qr_image_metadata', ['id'], unique=False)
    op.create_table('qr_payment_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('qr_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('payment_network', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('transaction_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['qr_investigation_id'], ['qr_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_investigation_id')
    )
    op.create_index(op.f('ix_qr_payment_metadata_id'), 'qr_payment_metadata', ['id'], unique=False)
    op.create_table('redirect_chains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('from_url', sa.String(), nullable=False),
    sa.Column('to_url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('redirect_type', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['url_investigation_id'], ['url_investigation_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirect_chains_id'), 'redirect_chains', ['id'], unique=False)
    op.create_table('routing_hops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('hop_index', sa.Integer(), nullable=True),
    sa.Column('receiving_server', sa.String(), nullable=True),
    sa.Column('sending_server', sa.String(), nullable=True),
    sa.Column('sending_ip', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['email_investigation_id'], ['email_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_hops_id'), 'routing_hops', ['id'], unique=False)
    op.create_table('security_header_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('content_security_policy', sa.String(), nullable=True),
    sa.Column('strict_transport_security', sa.String(), nullable=True),
    sa.Column('x_frame_options', sa.String(), nullable=True),
    sa.Column('x_content_type_options', sa.String(), nullable=True),
    sa.Column('referrer_policy', sa.String(), nullable=True),
    sa.Column('permissions_policy', sa.String(), nullable=True),
    sa.Column('has_mixed_content', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['website_investigation_id'], ['website_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_investigation_id')
    )
    op.create_index(op.f('ix_security_header_data_id'), 'security_header_data', ['id'], unique=False)
    op.create_table('signature_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('malware_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['malware_investigation_id'], ['malware_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_matches_id'), 'signature_matches', ['id'], unique=False)
    op.create_table('static_analysis_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('malware_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('imports', sa.JSON(), nullable=True),
    sa.Column('exports', sa.JSON(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('embedded_strings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['malware_investigation_id'], ['malware_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('malware_investigation_id')
    )
    op.create_index(op.f('ix_static_analysis_data_id'), 'static_analysis_data', ['id'], unique=False)
    op.create_table('visual_analysis_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('website_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('impersonates_brand', sa.Boolean(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('is_fake_login', sa.Boolean(), nullable=True),
    sa.Column('is_fake_banking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['website_investigation_id'], ['website_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_investigation_id')
    )
    op.create_index(op.f('ix_visual_analysis_data_id'), 'visual_analysis_data', ['id'], unique=False)
    op.create_table('visual_tampering_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('qr_investigation_id', sa.Uuid(), nullable=False),
    sa.Column('has_overlay_sticker', sa.Boolean(), nullable=True),
    sa.Column('has_logo_anomaly', sa.Boolean(), nullable=True),
    sa.Column('tampering_confidence', sa.Float(), nullable=True),
    sa.Column('detected_brand', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['qr_investigation_id'], ['qr_investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_investigation_id')
    )
    op.create_index(op.f('ix_visual_tampering_data_id'), 'visual_tampering_data', ['id'], unique=False)
    op.create_table('certificate_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('infrastructure_id', sa.Uuid(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject_alt_names', sa.JSON(), nullable=True),
    sa.Column('tls_version', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['infrastructure_id'], ['domain_infrastructures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_data_id'), 'certificate_data', ['id'], unique=False)
    op.alter_column('correlation_evidence', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('correlation_evidence', 'relationship_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('indicator', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('indicator_correlation', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('indicator_correlation', 'source_indicator_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('indicator_correlation', 'target_indicator_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('indicator_risk', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('indicator_risk', 'indicator_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('threat_feed_result', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('threat_feed_result', 'indicator_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threat_feed_result', 'indicator_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('threat_feed_result', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('indicator_risk', 'indicator_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('indicator_risk', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('indicator_correlation', 'target_indicator_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('indicator_correlation', 'source_indicator_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('indicator_correlation', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('indicator', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('correlation_evidence', 'relationship_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('correlation_evidence', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_certificate_data_id'), table_name='certificate_data')
    op.drop_table('certificate_data')
    op.drop_index(op.f('ix_visual_tampering_data_id'), table_name='visual_tampering_data')
    op.drop_table('visual_tampering_data')
    op.drop_index(op.f('ix_visual_analysis_data_id'), table_name='visual_analysis_data')
    op.drop_table('visual_analysis_data')
    op.drop_index(op.f('ix_static_analysis_data_id'), table_name='static_analysis_data')
    op.drop_table('static_analysis_data')
    op.drop_index(op.f('ix_signature_matches_id'), table_name='signature_matches')
    op.drop_table('signature_matches')
    op.drop_index(op.f('ix_security_header_data_id'), table_name='security_header_data')
    op.drop_table('security_header_data')
    op.drop_index(op.f('ix_routing_hops_id'), table_name='routing_hops')
    op.drop_table('routing_hops')
    op.drop_index(op.f('ix_redirect_chains_id'), table_name='redirect_chains')
    op.drop_table('redirect_chains')
    op.drop_index(op.f('ix_qr_payment_metadata_id'), table_name='qr_payment_metadata')
    op.drop_table('qr_payment_metadata')
    op.drop_index(op.f('ix_qr_image_metadata_id'), table_name='qr_image_metadata')
    op.drop_table('qr_image_metadata')
    op.drop_index(op.f('ix_parsed_urls_root_domain'), table_name='parsed_urls')
    op.drop_index(op.f('ix_parsed_urls_id'), table_name='parsed_urls')
    op.drop_index(op.f('ix_parsed_urls_hostname'), table_name='parsed_urls')
    op.drop_table('parsed_urls')
    op.drop_index(op.f('ix_page_snapshots_id'), table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index(op.f('ix_network_tls_metadata_server_name'), table_name='network_tls_metadata')
    op.drop_index(op.f('ix_network_tls_metadata_id'), table_name='network_tls_metadata')
    op.drop_table('network_tls_metadata')
    op.drop_index(op.f('ix_network_timeline_events_timestamp'), table_name='network_timeline_events')
    op.drop_index(op.f('ix_network_timeline_events_id'), table_name='network_timeline_events')
    op.drop_table('network_timeline_events')
    op.drop_index(op.f('ix_network_http_metadata_id'), table_name='network_http_metadata')
    op.drop_index(op.f('ix_network_http_metadata_host'), table_name='network_http_metadata')
    op.drop_table('network_http_metadata')
    op.drop_index(op.f('ix_network_flow_records_source_ip'), table_name='network_flow_records')
    op.drop_index(op.f('ix_network_flow_records_id'), table_name='network_flow_records')
    op.drop_index(op.f('ix_network_flow_records_destination_ip'), table_name='network_flow_records')
    op.drop_table('network_flow_records')
    op.drop_index(op.f('ix_network_extracted_iocs_id'), table_name='network_extracted_iocs')
    op.drop_table('network_extracted_iocs')
    op.drop_index(op.f('ix_network_dns_records_query'), table_name='network_dns_records')
    op.drop_index(op.f('ix_network_dns_records_id'), table_name='network_dns_records')
    op.drop_table('network_dns_records')
    op.drop_index(op.f('ix_mobile_timeline_events_timestamp'), table_name='mobile_timeline_events')
    op.drop_index(op.f('ix_mobile_timeline_events_id'), table_name='mobile_timeline_events')
    op.drop_table('mobile_timeline_events')
    op.drop_index(op.f('ix_mobile_locations_id'), table_name='mobile_locations')
    op.drop_table('mobile_locations')
    op.drop_index(op.f('ix_mobile_extracted_iocs_id'), table_name='mobile_extracted_iocs')
    op.drop_table('mobile_extracted_iocs')
    op.drop_index(op.f('ix_mobile_device_metadata_id'), table_name='mobile_device_metadata')
    op.drop_table('mobile_device_metadata')
    op.drop_index(op.f('ix_mobile_communications_id'), table_name='mobile_communications')
    op.drop_index(op.f('ix_mobile_communications_contact_number'), table_name='mobile_communications')
    op.drop_table('mobile_communications')
    op.drop_index(op.f('ix_mobile_applications_package_name'), table_name='mobile_applications')
    op.drop_index(op.f('ix_mobile_applications_id'), table_name='mobile_applications')
    op.drop_table('mobile_applications')
    op.drop_index(op.f('ix_malware_threat_correlations_id'), table_name='malware_threat_correlations')
    op.drop_table('malware_threat_correlations')
    op.drop_index(op.f('ix_malware_metadata_id'), table_name='malware_metadata')
    op.drop_table('malware_metadata')
    op.drop_index(op.f('ix_malware_hashes_sha256'), table_name='malware_hashes')
    op.drop_index(op.f('ix_malware_hashes_sha1'), table_name='malware_hashes')
    op.drop_index(op.f('ix_malware_hashes_md5'), table_name='malware_hashes')
    op.drop_index(op.f('ix_malware_hashes_id'), table_name='malware_hashes')
    op.drop_table('malware_hashes')
    op.drop_index(op.f('ix_malware_extracted_iocs_id'), table_name='malware_extracted_iocs')
    op.drop_table('malware_extracted_iocs')
    op.drop_index(op.f('ix_javascript_metadata_id'), table_name='javascript_metadata')
    op.drop_table('javascript_metadata')
    op.drop_index(op.f('ix_form_metadata_id'), table_name='form_metadata')
    op.drop_table('form_metadata')
    op.drop_index(op.f('ix_extracted_urls_id'), table_name='extracted_urls')
    op.drop_table('extracted_urls')
    op.drop_index(op.f('ix_email_header_data_id'), table_name='email_header_data')
    op.drop_table('email_header_data')
    op.drop_index(op.f('ix_domain_infrastructures_id'), table_name='domain_infrastructures')
    op.drop_index(op.f('ix_domain_infrastructures_domain_name'), table_name='domain_infrastructures')
    op.drop_table('domain_infrastructures')
    op.drop_index(op.f('ix_decoded_qr_payloads_id'), table_name='decoded_qr_payloads')
    op.drop_table('decoded_qr_payloads')
    op.drop_index(op.f('ix_copilot_messages_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_conversation_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_cloud_timeline_events_timestamp'), table_name='cloud_timeline_events')
    op.drop_index(op.f('ix_cloud_timeline_events_id'), table_name='cloud_timeline_events')
    op.drop_table('cloud_timeline_events')
    op.drop_index(op.f('ix_cloud_identities_identity_id'), table_name='cloud_identities')
    op.drop_index(op.f('ix_cloud_identities_id'), table_name='cloud_identities')
    op.drop_table('cloud_identities')
    op.drop_index(op.f('ix_cloud_extracted_iocs_id'), table_name='cloud_extracted_iocs')
    op.drop_table('cloud_extracted_iocs')
    op.drop_index(op.f('ix_cloud_configurations_resource_id'), table_name='cloud_configurations')
    op.drop_index(op.f('ix_cloud_configurations_id'), table_name='cloud_configurations')
    op.drop_table('cloud_configurations')
    op.drop_index(op.f('ix_cloud_audit_events_timestamp'), table_name='cloud_audit_events')
    op.drop_index(op.f('ix_cloud_audit_events_id'), table_name='cloud_audit_events')
    op.drop_index(op.f('ix_cloud_audit_events_event_name'), table_name='cloud_audit_events')
    op.drop_table('cloud_audit_events')
    op.drop_index(op.f('ix_cloud_assets_id'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_asset_type'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_asset_id'), table_name='cloud_assets')
    op.drop_table('cloud_assets')
    op.drop_index(op.f('ix_campaign_correlations_id'), table_name='campaign_correlations')
    op.drop_table('campaign_correlations')
    op.drop_index(op.f('ix_browser_timeline_events_timestamp'), table_name='browser_timeline_events')
    op.drop_index(op.f('ix_browser_timeline_events_id'), table_name='browser_timeline_events')
    op.drop_table('browser_timeline_events')
    op.drop_index(op.f('ix_browser_history_records_url'), table_name='browser_history_records')
    op.drop_index(op.f('ix_browser_history_records_id'), table_name='browser_history_records')
    op.drop_table('browser_history_records')
    op.drop_index(op.f('ix_browser_extracted_iocs_id'), table_name='browser_extracted_iocs')
    op.drop_table('browser_extracted_iocs')
    op.drop_index(op.f('ix_browser_extensions_id'), table_name='browser_extensions')
    op.drop_index(op.f('ix_browser_extensions_extension_id'), table_name='browser_extensions')
    op.drop_table('browser_extensions')
    op.drop_index(op.f('ix_browser_downloads_id'), table_name='browser_downloads')
    op.drop_table('browser_downloads')
    op.drop_index(op.f('ix_browser_cookies_id'), table_name='browser_cookies')
    op.drop_index(op.f('ix_browser_cookies_domain'), table_name='browser_cookies')
    op.drop_table('browser_cookies')
    op.drop_index(op.f('ix_brand_intelligence_id'), table_name='brand_intelligence')
    op.drop_table('brand_intelligence')
    op.drop_index(op.f('ix_authentication_results_id'), table_name='authentication_results')
    op.drop_table('authentication_results')
    op.drop_index(op.f('ix_attachment_metadata_sha256_hash'), table_name='attachment_metadata')
    op.drop_index(op.f('ix_attachment_metadata_id'), table_name='attachment_metadata')
    op.drop_table('attachment_metadata')
    op.drop_index(op.f('ix_website_investigations_url'), table_name='website_investigations')
    op.drop_index(op.f('ix_website_investigations_investigation_id'), table_name='website_investigations')
    op.drop_index(op.f('ix_website_investigations_id'), table_name='website_investigations')
    op.drop_table('website_investigations')
    op.drop_index(op.f('ix_url_investigation_details_investigation_id'), table_name='url_investigation_details')
    op.drop_index(op.f('ix_url_investigation_details_id'), table_name='url_investigation_details')
    op.drop_index(op.f('ix_url_investigation_details_canonical_url'), table_name='url_investigation_details')
    op.drop_table('url_investigation_details')
    op.drop_index(op.f('ix_reports_investigation_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_qr_investigations_investigation_id'), table_name='qr_investigations')
    op.drop_index(op.f('ix_qr_investigations_id'), table_name='qr_investigations')
    op.drop_index(op.f('ix_qr_investigations_file_name'), table_name='qr_investigations')
    op.drop_table('qr_investigations')
    op.drop_index(op.f('ix_network_investigations_investigation_id'), table_name='network_investigations')
    op.drop_index(op.f('ix_network_investigations_id'), table_name='network_investigations')
    op.drop_table('network_investigations')
    op.drop_index(op.f('ix_mobile_investigations_investigation_id'), table_name='mobile_investigations')
    op.drop_index(op.f('ix_mobile_investigations_id'), table_name='mobile_investigations')
    op.drop_index(op.f('ix_mobile_investigations_device_name'), table_name='mobile_investigations')
    op.drop_table('mobile_investigations')
    op.drop_index(op.f('ix_malware_investigations_sample_name'), table_name='malware_investigations')
    op.drop_index(op.f('ix_malware_investigations_investigation_id'), table_name='malware_investigations')
    op.drop_index(op.f('ix_malware_investigations_id'), table_name='malware_investigations')
    op.drop_table('malware_investigations')
    op.drop_index(op.f('ix_generated_reports_investigation_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_email_investigations_subject'), table_name='email_investigations')
    op.drop_index(op.f('ix_email_investigations_message_id'), table_name='email_investigations')
    op.drop_index(op.f('ix_email_investigations_investigation_id'), table_name='email_investigations')
    op.drop_index(op.f('ix_email_investigations_id'), table_name='email_investigations')
    op.drop_table('email_investigations')
    op.drop_index(op.f('ix_copilot_conversations_investigation_id'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_id'), table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    op.drop_index(op.f('ix_cloud_investigations_investigation_id'), table_name='cloud_investigations')
    op.drop_index(op.f('ix_cloud_investigations_id'), table_name='cloud_investigations')
    op.drop_index(op.f('ix_cloud_investigations_cloud_provider'), table_name='cloud_investigations')
    op.drop_table('cloud_investigations')
    op.drop_index(op.f('ix_browser_investigations_investigation_id'), table_name='browser_investigations')
    op.drop_index(op.f('ix_browser_investigations_id'), table_name='browser_investigations')
    op.drop_index(op.f('ix_browser_investigations_browser_type'), table_name='browser_investigations')
    op.drop_table('browser_investigations')
    op.drop_index(op.f('ix_alert_lifecycle_events_id'), table_name='alert_lifecycle_events')
    op.drop_index(op.f('ix_alert_lifecycle_events_alert_id'), table_name='alert_lifecycle_events')
    op.drop_table('alert_lifecycle_events')
    op.drop_index(op.f('ix_alert_evidence_value'), table_name='alert_evidence')
    op.drop_index(op.f('ix_alert_evidence_id'), table_name='alert_evidence')
    op.drop_index(op.f('ix_alert_evidence_alert_id'), table_name='alert_evidence')
    op.drop_table('alert_evidence')
    op.drop_index(op.f('ix_alert_assignments_user_id'), table_name='alert_assignments')
    op.drop_index(op.f('ix_alert_assignments_id'), table_name='alert_assignments')
    op.drop_index(op.f('ix_alert_assignments_alert_id'), table_name='alert_assignments')
    op.drop_table('alert_assignments')
    op.drop_index(op.f('ix_workflow_executions_version_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_case_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_ti_feed_indicator_version_id'), table_name='ti_feed_indicator')
    op.drop_index(op.f('ix_ti_feed_indicator_global_indicator_id'), table_name='ti_feed_indicator')
    op.drop_index(op.f('ix_ti_feed_indicator_feed_id'), table_name='ti_feed_indicator')
    op.drop_table('ti_feed_indicator')
    op.drop_index(op.f('ix_ti_feed_audit_log_feed_id'), table_name='ti_feed_audit_log')
    op.drop_table('ti_feed_audit_log')
    op.drop_index(op.f('ix_security_alerts_title'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_tenant_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_status'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_source_alert_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_source'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_priority_score'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_created_at'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_correlation_group_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_category'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_case_id'), table_name='security_alerts')
    op.drop_table('security_alerts')
    # ### end Alembic commands ###
